CONFIGS:
  DIABS_PATH: '../data/diabetes.csv'
  EXCLUDE_COLS: ['Outcome', 'Pregnancies']
  FEATURES: ['BloodPressure', 'BMI', 'Glucose', 'Insulin', 'SkinThickness']
  POLICY: 'mean'
  MODELS: ['mlp', 'rf', 'lr']
  BASELINES: [null, 0.5, 0.7, 0.9]

HYPERPARAMS:
  RANDOM_SEED: 7
  TEST_SIZE: 0.2