DATA:
  DATA_CONFIGS_PATH: "/Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/data_configs/stroke_full.yaml"


MODELS:
  MODEL_CONFIGS_PATHS:
    - /Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/linear_model_configs/lr_1.yaml
    - /Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/linear_model_configs/lr_2.yaml
    - /Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/svm_configs/svm_1.yaml
    - /Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/svm_configs/linear_svm_cc_1.yaml
    - /Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/ensemble_configs/random_forrest_cc_1.yaml

  ENSEMBLE_CONFIGS_PATH: "/Users/ag46548/dev/github/KaleRP/table15/src/table15/configs/model_configs/ensemble_configs/voting_classifier_1.yaml"
  USE_FEATURE_IMPORTANCE_SCALING: false


DEBUGGING:
  USE_MULTIPROCESSING: false
