CONFIGS:
  CSV_PATH: '/Users/ag46548/dev/github/KaleRP/table15/src/data/diabetes.csv'
  POLICY: 'mean'
  MODELS: ['lr', 'rf', 'mlp']
  BASELINES: [1, 0.5, 0.3, 0.1]

HYPERPARAMS:
  RANDOM_SEED: 7
  TEST_SIZE: 0.2

FEATURES:
  NUMERICAL: ['BloodPressure', 'BMI', 'Glucose', 'Insulin', 'SkinThickness']
  CATEGORICAL: []
  BINARY: []
  TARGET: ['Outcome']
  SET_FEATURE_VALUES:
    Insulin: 45
    bmi: 20

MODELS:
  USE_ENSEMBLE: false
  SKIP_MULTIPROCESSING: false
  NUM_MODELS_RANK: 3
  